name: Analyze CVEs

permissions:
  contents: read

on:
  schedule:
    - cron: "0 10 * * *"
  pull_request:
    paths:
      - "go.mod"
      - "go.sum"
      - "cargo.toml"
      - "cargo.lock"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup golang
        uses: ./.github/actions/golang

      - name: Install tools
        uses: ./.github/actions/install-tools

      - name: Check for CVEs in Dependencies
        run: "make test-cves"
